In [290]:
import pandas as pd
import numpy as np
import plotly.express as px

In [291]:
# Function to output outliers in the column that we input using IQR
def find_outliers_IQR(df_cleaned):
  q1=df_cleaned.quantile(0.25)
  q3=df_cleaned.quantile(0.75)
  IQR=q3-q1
  outliers = df_cleaned[((df_cleaned<(q1-1.5*IQR))|(df_cleaned>(q3+1.5*IQR)))]
  return outliers

In [292]:
df=pd.read_csv('Dementia Prediction Dataset.csv')
df.head(5)

C:\Users\IksuraW\AppData\Local\Temp\ipykernel_26732\239156467.py:1: DtypeWarning:

Columns (20,22,24,26,28,41,44,46,48,51,61,63,65,67,69,71,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,134,156,165,176,179,189,217,220,222,224,226,228,230,232,234,236,238,240,242,244,246,248,250,252,254,256,258,260,262,264,266,268,270,272,382,397,399,401,419,421,423,432,445,454,494,574,605,613,638,674,690,704,707,710,715,727,738,744,746,803,804,809,810,811,812,820,831,833,835,837,843,904,959,960,961,969,970,971,972,982,1004,1007,1010) have mixed types. Specify dtype option on import or set low_memory=False.



NACCID  NACCADC PACKET  FORMVER  VISITMO  VISITDAY  VISITYR  NACCVNUM  \
0  NACC002909      186      I      3.0       12        28     2022         1   
1  NACC002909      186      F      3.0        1        23     2024         2   
2  NACC003487      186      I      3.0       11        15     2023         1   
3  NACC004352      186      I      3.0       10         5     2021         1   
4  NACC004687      186      I      3.0       11        14     2022         1   

   NACCAVST  NACCNVST  ...  NPATGAM1  NPATGAM2  NPATGAM3  NPATGAM4  NPATGAM5  \
0         2         2  ...        -4        -4        -4        -4        -4   
1         2         2  ...        -4        -4        -4        -4        -4   
2         1         1  ...        -4        -4        -4        -4        -4   
3         1         1  ...        -4        -4        -4        -4        -4   
4         1         1  ...        -4        -4        -4        -4        -4   

   NPATGFRN  NPATGFR1  NPATGFR2  NPATGFR3  NPATGFR4  
0        -4        -4        -4        -4        -4  
1        -4        -4        -4        -4        -4  
2        -4        -4        -4        -4        -4  
3        -4        -4        -4        -4        -4  
4        -4        -4        -4        -4        -4  

[5 rows x 1024 columns]

In [293]:
df.shape

(195196, 1024)

In [294]:
selected_columns = [
    
    #T1 and A1
    "BIRTHMO","BIRTHYR","SEX","HISPOR","PRIMLANG","EDUC","MARISTAT","NACCLIVS","INDEPEND","RESIDENC","HANDED",
    #A2
    "INSEX","INRELTO","INKNOWN","INLIVWTH","INCALLS","INVISITS","INRELY",
    #A4
    "ANYMEDS","NACCAHTN","NACCLIPL","NACCDBMD",
    #A5
    #Smoking history
    "TOBAC30","TOBAC100","SMOKYRS","PACKSPER","QUITSMOK",
    "ALCOCCAS","ALCFREQ",
    "CVHATT","HATTMULT","HATTYEAR",
    "CVAFIB","CVANGIO","CVBYPASS","CVPACDEF","CVPACE","CVCHF","CVANGINA","CVHVALVE","CVOTHR","CBSTROKE",
    "CBTIA","PD","PDOTHR","PDOTHRYR",
    "SEIZURES",
    "TBI","TBIBRIEF","TRAUMBRF","TBIEXTEN","TRAUMEXT","TBIYEAR",
    "NCOTHR",
    "DIABETES","DIABTYPE",
    "HYPERTEN","HYPERCHO","B12DEF","THYROID",
    "ARTHRIT","ARTHTYPE","ARTHUPEX","ARTHLOEX","ARTHSPIN","ARTHUNK",
    "INCONTF",
    "APNEA","RBD","INSOMN","OTHSLEEP",
    "ALCOHOL","ABUSOTHR","PTSD","BIPOLAR","SCHIZ","DEP2YRS",
    "DEPOTHR","ANXIETY","OCD","NPSYDEV","PSYCDIS","NACCTBI",
    #B1
    "VISION","VISCORR","VISWCORR"
    ,"HEARING","HEARAID","HXSTROKE","HXHYPER",
    #Target variable
    "DEMENTED"
    ]

In [295]:
df_cleaned = df[selected_columns].copy()
df.head(10)

NACCID  NACCADC PACKET  FORMVER  VISITMO  VISITDAY  VISITYR  NACCVNUM  \
0  NACC002909      186      I      3.0       12        28     2022         1   
1  NACC002909      186      F      3.0        1        23     2024         2   
2  NACC003487      186      I      3.0       11        15     2023         1   
3  NACC004352      186      I      3.0       10         5     2021         1   
4  NACC004687      186      I      3.0       11        14     2022         1   
5  NACC007213      186      I      3.0        5        24     2023         1   
6  NACC008514      186      I      3.0       11        15     2022         1   
7  NACC008514      186      F      3.0       12        20     2023         2   
8  NACC013204      186      I      3.0        8         7     2023         1   
9  NACC013667      186      I      3.0        3        29     2022         1   

   NACCAVST  NACCNVST  ...  NPATGAM1  NPATGAM2  NPATGAM3  NPATGAM4  NPATGAM5  \
0         2         2  ...        -4        -4        -4        -4        -4   
1         2         2  ...        -4        -4        -4        -4        -4   
2         1         1  ...        -4        -4        -4        -4        -4   
3         1         1  ...        -4        -4        -4        -4        -4   
4         1         1  ...        -4        -4        -4        -4        -4   
5         1         1  ...        -4        -4        -4        -4        -4   
6         2         2  ...        -4        -4        -4        -4        -4   
7         2         2  ...        -4        -4        -4        -4        -4   
8         1         1  ...        -4        -4        -4        -4        -4   
9         1         1  ...        -4        -4        -4        -4        -4   

   NPATGFRN  NPATGFR1  NPATGFR2  NPATGFR3  NPATGFR4  
0        -4        -4        -4        -4        -4  
1        -4        -4        -4        -4        -4  
2        -4        -4        -4        -4        -4  
3        -4        -4        -4        -4        -4  
4        -4        -4        -4        -4        -4  
5        -4        -4        -4        -4        -4  
6        -4        -4        -4        -4        -4  
7        -4        -4        -4        -4        -4  
8        -4        -4        -4        -4        -4  
9        -4        -4        -4        -4        -4  

[10 rows x 1024 columns]

In [296]:
df_cleaned.shape

(195196, 91)

In [297]:
# Checking the total number of missing values in the dataset
df_cleaned.isnull().sum()

BIRTHMO     0
BIRTHYR     0
SEX         0
HISPOR      0
PRIMLANG    0
EDUC        0
MARISTAT    0
NACCLIVS    0
INDEPEND    0
RESIDENC    0
HANDED      0
INSEX       0
INRELTO     0
INKNOWN     0
INLIVWTH    0
INCALLS     0
INVISITS    0
INRELY      0
ANYMEDS     0
NACCAHTN    0
NACCLIPL    0
NACCDBMD    0
TOBAC30     0
TOBAC100    0
SMOKYRS     0
PACKSPER    0
QUITSMOK    0
ALCOCCAS    0
ALCFREQ     0
CVHATT      0
HATTMULT    0
HATTYEAR    0
CVAFIB      0
CVANGIO     0
CVBYPASS    0
CVPACDEF    0
CVPACE      0
CVCHF       0
CVANGINA    0
CVHVALVE    0
CVOTHR      0
CBSTROKE    0
CBTIA       0
PD          0
PDOTHR      0
PDOTHRYR    0
SEIZURES    0
TBI         0
TBIBRIEF    0
TRAUMBRF    0
TBIEXTEN    0
TRAUMEXT    0
TBIYEAR     0
NCOTHR      0
DIABETES    0
DIABTYPE    0
HYPERTEN    0
HYPERCHO    0
B12DEF      0
THYROID     0
ARTHRIT     0
ARTHTYPE    0
ARTHUPEX    0
ARTHLOEX    0
ARTHSPIN    0
ARTHUNK     0
INCONTF     0
APNEA       0
RBD         0
INSOMN      0
OTHSLEEP    0
ALCOHO

In [298]:
# Checking the null value precentage
df_cleaned.isna().sum()/len(df_cleaned)*100

BIRTHMO     0.0
BIRTHYR     0.0
SEX         0.0
HISPOR      0.0
PRIMLANG    0.0
EDUC        0.0
MARISTAT    0.0
NACCLIVS    0.0
INDEPEND    0.0
RESIDENC    0.0
HANDED      0.0
INSEX       0.0
INRELTO     0.0
INKNOWN     0.0
INLIVWTH    0.0
INCALLS     0.0
INVISITS    0.0
INRELY      0.0
ANYMEDS     0.0
NACCAHTN    0.0
NACCLIPL    0.0
NACCDBMD    0.0
TOBAC30     0.0
TOBAC100    0.0
SMOKYRS     0.0
PACKSPER    0.0
QUITSMOK    0.0
ALCOCCAS    0.0
ALCFREQ     0.0
CVHATT      0.0
HATTMULT    0.0
HATTYEAR    0.0
CVAFIB      0.0
CVANGIO     0.0
CVBYPASS    0.0
CVPACDEF    0.0
CVPACE      0.0
CVCHF       0.0
CVANGINA    0.0
CVHVALVE    0.0
CVOTHR      0.0
CBSTROKE    0.0
CBTIA       0.0
PD          0.0
PDOTHR      0.0
PDOTHRYR    0.0
SEIZURES    0.0
TBI         0.0
TBIBRIEF    0.0
TRAUMBRF    0.0
TBIEXTEN    0.0
TRAUMEXT    0.0
TBIYEAR     0.0
NCOTHR      0.0
DIABETES    0.0
DIABTYPE    0.0
HYPERTEN    0.0
HYPERCHO    0.0
B12DEF      0.0
THYROID     0.0
ARTHRIT     0.0
ARTHTYPE    0.0
ARTHUPEX

In [299]:
# Displays all the column names and the data types of each column
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195196 entries, 0 to 195195
Data columns (total 91 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   BIRTHMO   195196 non-null  int64
 1   BIRTHYR   195196 non-null  int64
 2   SEX       195196 non-null  int64
 3   HISPOR    195196 non-null  int64
 4   PRIMLANG  195196 non-null  int64
 5   EDUC      195196 non-null  int64
 6   MARISTAT  195196 non-null  int64
 7   NACCLIVS  195196 non-null  int64
 8   INDEPEND  195196 non-null  int64
 9   RESIDENC  195196 non-null  int64
 10  HANDED    195196 non-null  int64
 11  INSEX     195196 non-null  int64
 12  INRELTO   195196 non-null  int64
 13  INKNOWN   195196 non-null  int64
 14  INLIVWTH  195196 non-null  int64
 15  INCALLS   195196 non-null  int64
 16  INVISITS  195196 non-null  int64
 17  INRELY    195196 non-null  int64
 18  ANYMEDS   195196 non-null  int64
 19  NACCAHTN  195196 non-null  int64
 20  NACCLIPL  195196 non-null  int64
 21  NACCDBMD  

In [300]:
df_cleaned.dtypes

BIRTHMO     int64
BIRTHYR     int64
SEX         int64
HISPOR      int64
PRIMLANG    int64
EDUC        int64
MARISTAT    int64
NACCLIVS    int64
INDEPEND    int64
RESIDENC    int64
HANDED      int64
INSEX       int64
INRELTO     int64
INKNOWN     int64
INLIVWTH    int64
INCALLS     int64
INVISITS    int64
INRELY      int64
ANYMEDS     int64
NACCAHTN    int64
NACCLIPL    int64
NACCDBMD    int64
TOBAC30     int64
TOBAC100    int64
SMOKYRS     int64
PACKSPER    int64
QUITSMOK    int64
ALCOCCAS    int64
ALCFREQ     int64
CVHATT      int64
HATTMULT    int64
HATTYEAR    int64
CVAFIB      int64
CVANGIO     int64
CVBYPASS    int64
CVPACDEF    int64
CVPACE      int64
CVCHF       int64
CVANGINA    int64
CVHVALVE    int64
CVOTHR      int64
CBSTROKE    int64
CBTIA       int64
PD          int64
PDOTHR      int64
PDOTHRYR    int64
SEIZURES    int64
TBI         int64
TBIBRIEF    int64
TRAUMBRF    int64
TBIEXTEN    int64
TRAUMEXT    int64
TBIYEAR     int64
NCOTHR      int64
DIABETES    int64
DIABTYPE  

In [301]:
for col in selected_columns:
    df_cleaned[col] = df_cleaned[col].replace({-4: None})

In [302]:
for col in selected_columns:
    print(f"\n---- {col} ----")
    print(df_cleaned[col].unique())


---- BIRTHMO ----
[ 5 12  1  2  7  8 10 11  3  6  9  4]

---- BIRTHYR ----
[1952 1956 1958 1945 1942 1936 1949 1957 1951 1950 1947 1948 1963 1959
 1938 1953 1941 1940 1971 1930 1954 1939 1946 1944 1973 1960 1962 1965
 1943 1964 1934 1937 1935 1928 2000 1955 1975 1969 1961 1974 1933 1976
 1978 1967 1984 1972 1966 1981 1970 1929 1990 1968 1931 1992 1979 1932
 1993 1926 1980 1920 1985 1921 1986 1927 1925 2002 1977 1991 1919 1989
 1983 1913 1924 1982 1923 1987 1918 1917 1922 1995 1994 1914 2003 1999
 1988 1915 1916 1912 1910 1911 1907 1996 1909 1998 1997 2001 2004 1908
 1906 1905 1901 1902 1896 1904 2005 1903]

---- SEX ----
[1 2]

---- HISPOR ----
[88  1 99  2 50  5  6  3  4]

---- PRIMLANG ----
[1 2 8 3 6 4 9 5]

---- EDUC ----
[16 12  7 20 18 14  9  6 11 13  1 17 19 15  4  3  8 99  5 10  0  2 25 24
 22 21 26 27 30 23 28 31 29]

---- MARISTAT ----
[1 3 5 6 2 4 9]

---- NACCLIVS ----
[4 2 1 3 5 9]

---- INDEPEND ----
[1 2 3 4 9]

---- RESIDENC ----
[1 2 9 3 4]

---- HANDED ----
[2 1 3 9]

In [303]:
df_cleaned["HISPOR"] = df_cleaned["HISPOR"].replace({99: None,88:None})
print(df_cleaned["HISPOR"].unique())

[None 1 2 50 5 6 3 4]


In [304]:
df_cleaned["EDUC "] = df_cleaned["EDUC"].replace({99: None})
print(df_cleaned["EDUC"].unique())

[16 12  7 20 18 14  9  6 11 13  1 17 19 15  4  3  8 99  5 10  0  2 25 24
 22 21 26 27 30 23 28 31 29]


In [305]:
df_cleaned["QUITSMOK"] = df_cleaned["QUITSMOK"].replace({999: None,888:None})
print(df_cleaned["QUITSMOK"].unique())

[None 42 29 12 68 32 47 55 61 21 40 22 20 35 28 52 19 48 33 39 25 50 77 37
 60 45 70 63 8 57 16 64 79 51 26 56 30 36 17 24 62 27 34 73 15 49 59 58 38
 54 46 18 23 65 76 31 67 43 53 41 44 69 71 75 78 72 66 74 85 95 84 83 89
 13 94 82 14 81 80 91 88 10 11 9 87 92 90 86 97 99 100 96 93]


In [306]:
df_cleaned["PDOTHRYR"] = df_cleaned["PDOTHRYR"].replace({999: None,8888:None})
print(df_cleaned["PDOTHRYR"].unique())

[None 2023 2021 9999 2010 2020 2022 2008 2005 2006 2004 2011 2018 2007
 2013 2009 2017 1999 2016 2012 2002 2014 2015 2003 2001 2019 1959 1995
 2000 1991 1988 1986 1990 1974 1935 2024 1983 1996 1997 1998 1989 1987
 1965 1950 1930 1937 1924 1982 1993 1960 1947 1957 1953 1946 1977 1994
 1978 1969]


In [307]:
outlier_columns = [
    "BIRTHYR","INKNOWN",
    "SMOKYRS","HATTYEAR",
    "TBIYEAR"
]

In [308]:
for col in outlier_columns:    
    # Using find_outliers_IQR function to find outliers in Age
    outliers = find_outliers_IQR(df_cleaned[col])
    print(f"Number of outliers= [{col}]"+ str(len(outliers)))
    outliers

Number of outliers= [BIRTHYR]1747


Number of outliers= [INKNOWN]1094
Number of outliers= [SMOKYRS]6290
Number of outliers= [HATTYEAR]687
Number of outliers= [TBIYEAR]3195


In [309]:
df_cleaned["INKNOWN"] = df_cleaned["INKNOWN"].replace({999: None})
outliers = find_outliers_IQR(df_cleaned['INKNOWN'])
print("Number of outliers= INKNOWN "+ str(len(outliers)))
print(df_cleaned['INKNOWN'].unique())
outliers
#according to the DATA dictionary (1-120) is allowable codes 99 is within 1-120  

Number of outliers= INKNOWN 44
[8 None 40 65 56 55 37 54 44 20 57 32 46 45 77 41 22 63 38 21 66 58 14 49
 62 59 47 64 52 42 31 61 43 29 1 51 53 76 50 60 33 12 39 18 13 70 16 75 35
 30 48 5 2 6 27 26 17 25 24 28 0 72 36 67 73 10 71 11 68 34 3 23 4 80 15
 74 19 69 7 9 99 83 78 81 84 82 79 87 85 86 88 89]


14059     99
39776     99
51168     99
54951     99
56056     99
56544     99
57269     99
57427     99
57744     99
58414     99
58640     99
58698     99
59217     99
59590     99
59616     99
60261     99
60445     99
60603     99
64640     99
75305     99
75684     99
75685     99
77717     99
79930     99
80093     99
81390     99
81795     99
109107    99
132526    99
132858    99
134420    99
135166    99
135265    99
135597    99
136712    99
136749    99
137113    99
137816    99
165499    99
167912    99
171054    99
175675    99
179886    99
180346    99
Name: INKNOWN, dtype: object

In [310]:
df_cleaned["SMOKYRS"] = df_cleaned["SMOKYRS"].replace({99: None,88:None})
outliers = find_outliers_IQR(df_cleaned['SMOKYRS'])
print("Number of outliers= SMOKYRS "+ str(len(outliers)))
print(df_cleaned['SMOKYRS'].unique())
outliers
#in this we cant remove the outliers because (0-87) is the acceptable codes

Number of outliers= SMOKYRS 4658
[0 None 27 4 2 58 16 32 6 50 5 22 3 1 14 40 20 30 45 15 24 10 60 34 25 28
 17 35 42 48 36 8 39 33 18 11 57 12 21 46 55 23 26 52 38 7 61 47 13 9 31
 53 59 29 56 19 44 51 41 37 54 80 70 49 65 72 73 63 43 64 62 67 75 69 66
 68 74 76 77 78 81 82 71 79 84]


18        58
26        50
194       50
210       60
281       48
286       60
347       50
379       57
394       60
434       58
509       46
513       55
571       48
626       52
725       58
726       50
792       61
810       60
811       47
920       60
1113      50
1151      50
1327      50
1328      55
1383      53
1806      50
2086      59
2338      56
2339      56
2377      55
2379      55
2527      50
2591      53
2592      53
2702      50
2833      46
3081      50
3175      50
3195      50
3212      50
3361      50
3489      50
3490      50
3700      47
3728      50
3772      50
3773      51
3776      50
3931      50
3968      53
3969      53
4060      55
4196      46
4199      60
4505      50
4718      50
4719      56
4785      50
4879      53
4880      54
4881      54
4920      50
4952      54
4953      55
5275      50
5300      46
5543      80
5614      55
5615      50
6027      50
6207      70
6253      50
6429      49
6454      50
6455      50
6456      50
6457      50

In [311]:
df_cleaned["HATTYEAR"] = df_cleaned["HATTYEAR"].replace({9999: None,8888:None})
outliers = find_outliers_IQR(df_cleaned['HATTYEAR'])
print("Number of outliers= HATTYEAR "+ str(len(outliers)))
print(df_cleaned['HATTYEAR'].unique())
outliers

Number of outliers= HATTYEAR 12
[None 2016 2003 2007 1992 2021 2018 1995 2020 1999 2015 2012 2008 2009
 2019 2004 2005 1983 2013 2006 2011 2017 2014 1986 1998 1963 1997 2001
 2023 1991 2002 1988 1990 2010 1980 1958 2000 1985 1976 1987 1993 2022
 1965 1994 1969 2024 1982 1984 1996 1989 1972 1978]


6978      1963
17346     1980
19100     1958
19722     1976
23034     1965
25309     1969
39408     1980
40384     1980
50314     1982
50800     1982
170860    1972
191312    1978
Name: HATTYEAR, dtype: object

In [312]:
df_cleaned["TBIYEAR"] = df_cleaned["TBIYEAR"].replace({9999: None,8888:None})
outliers = find_outliers_IQR(df_cleaned['TBIYEAR'])
print("Number of outliers= TBIYEAR "+ str(len(outliers)))
print(df_cleaned['TBIYEAR'].unique())
outliers

Number of outliers= TBIYEAR 0
[1967 None 2018 1992 1999 2021 2006 1960 1972 2015 1956 2011 1949 1962
 2001 1987 1963 2022 2019 1974 1961 1995 1986 1957 1970 1975 2016 2017
 2000 2005 2023 1981 1979 1969 2013 1980 1985 2014 2020 1958 1964 2007
 1977 1973 1997 1994 1978 1990 1965 1996 1959 1976 2004 1966 1983 1988
 2009 1984 2008 1989 1946 1982 1968 1955 2010 2012 1991 1993 1950 1971
 2002 2003 1952 1998 1954 1953 1951 1938 1948 1945 2024 1947 1944 1936
 1943 1942 1934 1939 1941 1940 1930]


Series([], Name: TBIYEAR, dtype: object)

In [313]:
# Checking the total number of missing values in the dataset
df.isnull().sum()

NACCID            0
NACCADC           0
PACKET            0
FORMVER           0
VISITMO           0
VISITDAY          0
VISITYR           0
NACCVNUM          0
NACCAVST          0
NACCNVST          0
NACCDAYS          0
NACCFDYS          0
NACCCORE          0
NACCREAS          0
NACCREFR          0
BIRTHMO           0
BIRTHYR           0
SEX               0
HISPANIC          0
HISPOR            0
HISPORX      194669
RACE              0
RACEX        192851
RACESEC           0
RACESECX     194813
RACETER           0
RACETERX     195160
PRIMLANG          0
PRIMLANX     192464
EDUC              0
MARISTAT          0
NACCLIVS          0
INDEPEND          0
RESIDENC          0
HANDED            0
INBIRMO           0
INBIRYR           0
INSEX             0
NEWINF            0
INHISP            0
INHISPOR          0
INHISPOX     194958
NACCNINR          0
INRACE            0
INRACEX      193608
INRASEC           0
INRASECX     194899
INRATER           0
INRATERX     195137
INEDUC            0


In [314]:
pd.set_option('display.max_rows', None)
df_cleaned.isna().sum()/len(df_cleaned)*100

BIRTHMO      0.000000
BIRTHYR      0.000000
SEX          0.000000
HISPOR      93.190947
PRIMLANG     0.000000
EDUC         0.000000
MARISTAT     0.000000
NACCLIVS     0.000000
INDEPEND     0.000000
RESIDENC     0.000000
HANDED       0.000000
INSEX        4.245989
INRELTO      4.245989
INKNOWN     88.362466
INLIVWTH     4.245989
INCALLS      4.245989
INVISITS     4.245989
INRELY       4.245989
ANYMEDS      1.403205
NACCAHTN     1.403205
NACCLIPL     1.403205
NACCDBMD     1.403205
TOBAC30     36.713867
TOBAC100    36.713867
SMOKYRS     38.710834
PACKSPER    36.713867
QUITSMOK    75.134736
ALCOCCAS    89.936269
ALCFREQ     90.099182
CVHATT      36.713867
HATTMULT    89.994160
HATTYEAR    99.691080
CVAFIB      36.713867
CVANGIO     36.713867
CVBYPASS    36.713867
CVPACDEF    89.936269
CVPACE      46.777598
CVCHF       36.713867
CVANGINA    89.936269
CVHVALVE    89.936269
CVOTHR      36.713867
CBSTROKE    36.713867
CBTIA       36.713867
PD          36.713867
PDOTHR      36.713867
PDOTHRYR  

In [315]:
columns_to_drop = [

    # Extremely high missing values (>70%)
    "HISPOR", "INKNOWN", "QUITSMOK", "ALCOCCAS", "ALCFREQ",
    "HATTMULT", "HATTYEAR", "CVPACE", "CVPACDEF", "CVANGINA",
    "ARTHRIT", "ARTHTYPE", "ARTHUPEX", "ARTHLOEX", "ARTHSPIN",
    "ARTHUNK", "APNEA", "RBD", "INSOMN", "OTHSLEEP",
    "PTSD","PDOTHRYR", "BIPOLAR", "SCHIZ", "ANXIETY", "OCD",
    "TBI", "TBIBRIEF", "TBIEXTEN","TBIYEAR","CVHVALVE","NPSYDEV"
    ,"HXHYPER","HXSTROKE","TRAUMEXT","TRAUMBRF","NCOTHR"
]

In [316]:
df_cleaned = df_cleaned.drop(columns=columns_to_drop)

In [317]:
pd.set_option('display.max_rows', None)
df_cleaned.isna().sum()/len(df_cleaned)*100

BIRTHMO      0.000000
BIRTHYR      0.000000
SEX          0.000000
PRIMLANG     0.000000
EDUC         0.000000
MARISTAT     0.000000
NACCLIVS     0.000000
INDEPEND     0.000000
RESIDENC     0.000000
HANDED       0.000000
INSEX        4.245989
INRELTO      4.245989
INLIVWTH     4.245989
INCALLS      4.245989
INVISITS     4.245989
INRELY       4.245989
ANYMEDS      1.403205
NACCAHTN     1.403205
NACCLIPL     1.403205
NACCDBMD     1.403205
TOBAC30     36.713867
TOBAC100    36.713867
SMOKYRS     38.710834
PACKSPER    36.713867
CVHATT      36.713867
CVAFIB      36.713867
CVANGIO     36.713867
CVBYPASS    36.713867
CVCHF       36.713867
CVOTHR      36.713867
CBSTROKE    36.713867
CBTIA       36.713867
PD          36.713867
PDOTHR      36.713867
SEIZURES    36.713867
DIABETES    36.713867
DIABTYPE    36.713867
HYPERTEN    36.713867
HYPERCHO    36.713867
B12DEF      36.713867
THYROID     36.713867
INCONTF     36.713867
ALCOHOL     36.713867
ABUSOTHR    36.713867
DEP2YRS     36.713867
DEPOTHR   

In [325]:
df_cleaned.shape

(195196, 55)

In [326]:
df_prepared = df_cleaned.dropna()

print("=== DATASET PREPARATION SUMMARY ===")
print(f"Original shape: {df.shape}")
print(f"Prepared shape: {df_prepared.shape}")
print(f"Null values in prepared data: {df_prepared.isnull().sum().sum()}")

output_filename = 'prepared_medical_dataset.csv'
df_prepared.to_csv(output_filename, index=False)

print(f"Dataset successfully saved as: {output_filename}")
print(f"File contains: {df_prepared.shape[0]} rows and {df_prepared.shape[1]} columns")


=== DATASET PREPARATION SUMMARY ===
Original shape: (195196, 1024)
Prepared shape: (106523, 55)
Null values in prepared data: 0
Dataset successfully saved as: prepared_medical_dataset.csv
File contains: 106523 rows and 55 columns
